package com.example.praisebackend.models.auditLog;

public enum LogType {
    REQUEST_SELLER_DATA,
    USER_BANNED,
    USER_UNBANNED,
    CHANGE_PASSWORD,
    PRODUCT_UNSUSPENDED,
    PRODUCT_ADDED,
    PRODUCT_SUSPENDED,
    PRODUCT_DELETED,
    DELETE_EMAIL,
    DELETE_COMPLAINT,
    RESOLVE_COMPLAINT,
    UPDATE_COMPLAINT,
    MARK_AS_SOLD,
    UNMARK_AS_SOLD
}
